baseURL = 'https://creativeartatolye.com/'
relativeURLs = "True"
languageCode = 'tr-tr'
paginate = 6
theme= "cohub"
title = 'Creative Art Atölye'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Eğitmenlerimiz"
  url= "#investor"
  weight = 1
  [[menu.Main]]
  name = "Dersler"
  url= "#service"
  weight = 2
  [[menu.Main]]
  name = "Hakkında"
  url= "/about/"
  weight = 3
  [[menu.Main]]
  name = "Blog"
  url= "#blog"
  weight = 4
  #[[menu.Main]]
  #name = "Fiyatlar"
  #url= "#pricing"
  #weight = 5
  [[menu.Main]]
  name = "İletişim"
  url= "/contact/"
  weight = 6

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Gizlilik Sözleşmesi"
  url = "/privacy/"
  

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} Creative Art Atolye ."
  formspreeURL = "https://formspree.io/mbjwlead"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo-white.png"
  footerlogo = "images/logoo.png"
  footerDescription = ""
  
  [params.address]
  address = "İstanbul/Turkiye"
  email = "atolyecreativeart@gmail.com"
  openingDesc = "İstediğiniz zaman bizi arayabilir ve bilgi alabilirsiniz."
  #openingHours = "We are open from 7am — 7pm week days."
  phone = "+(90) 0506 125 98 89"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "41.015137"
  longitude = "28.979530"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/creativeartatolye/"
  weight = 1
  
  